import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//grabbing some functions for data pulling
import { getPersonIds, getPersonData, getList } from '../lib/persons';
import { getResourceIds, getResourceData } from '../lib/resources';


export async function getStaticProps(){
  const idData = await getList();
  console.log("the data received on the home page from getStaticProps is: ");
  console.log("------------------");
  console.log(idData);
  return{
    props: {
      idData,
    }
  };
}


export default function Home( {idData} ) {
  console.log("Home function: ", idData);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          List of ID's from Firebase!
        </h1>

        <div className="list-group col-6">

          {idData.map(({ id, name }) => (
            <Link key={id} href={`/persons/${id}`}>
                <a className="list-group-item list-group-item-action"> {name} </a>
            </Link>
          ))}
        </div>

      </main>

    </div>
  );
}